.class Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;
.super Lcom/brakefield/infinitestudio/ui/collections/CollectionItemViewHolder;
.source "BrushPackManager.java"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/brakefield/painter/brushes/BrushPackManager;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0xa
    name = "BrushViewHolder"
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lcom/brakefield/infinitestudio/ui/collections/CollectionItemViewHolder<",
        "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
        ">;"
    }
.end annotation


# instance fields
.field binding:Lcom/brakefield/painter/databinding/BrushCardBinding;


# direct methods
.method public constructor <init>(Landroid/view/View;Lcom/brakefield/infinitestudio/ui/collections/CollectionViewController$CollectionViewControllerDelegate;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Landroid/view/View;",
            "Lcom/brakefield/infinitestudio/ui/collections/CollectionViewController$CollectionViewControllerDelegate<",
            "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
            ">;)V"
        }
    .end annotation

    .line 276
    invoke-direct {p0, p1, p2}, Lcom/brakefield/infinitestudio/ui/collections/CollectionItemViewHolder;-><init>(Landroid/view/View;Lcom/brakefield/infinitestudio/ui/collections/CollectionViewController$CollectionViewControllerDelegate;)V

    .line 277
    invoke-static {p1}, Lcom/brakefield/painter/databinding/BrushCardBinding;->bind(Landroid/view/View;)Lcom/brakefield/painter/databinding/BrushCardBinding;

    move-result-object p1

    iput-object p1, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    .line 278
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->setItemClickListener()V

    .line 279
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->setItemLongClickListener()V

    .line 280
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->setItemContextClickListener()V

    .line 281
    iget-object p1, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-static {p1}, Lcom/brakefield/infinitestudio/ui/UIManager;->setPressAction(Landroid/view/View;)V

    return-void
.end method


# virtual methods
.method public update(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 11

    .line 287
    iget-boolean v0, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    .line 288
    iget-object v1, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->delegate:Lcom/brakefield/infinitestudio/ui/collections/CollectionViewController$CollectionViewControllerDelegate;

    check-cast v1, Lcom/brakefield/painter/brushes/BrushPackManager$BrushPackCollectionViewDelegate;

    invoke-virtual {v1}, Lcom/brakefield/painter/brushes/BrushPackManager$BrushPackCollectionViewDelegate;->getCurrentBrushFolder()Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;

    move-result-object v1

    const/4 v2, 0x1

    const/4 v3, 0x0

    if-nez v0, :cond_1

    .line 289
    invoke-virtual {v1}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->isAutoGenerated()Z

    move-result v4

    if-eqz v4, :cond_1

    .line 290
    iget-object v0, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->folder:Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;

    if-eq v0, v1, :cond_0

    move v0, v2

    goto :goto_0

    :cond_0
    move v0, v3

    .line 293
    :cond_1
    :goto_0
    iget-object v1, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-virtual {v1}, Landroid/view/View;->getLayoutParams()Landroid/view/ViewGroup$LayoutParams;

    move-result-object v1

    check-cast v1, Landroidx/recyclerview/widget/RecyclerView$LayoutParams;

    if-eqz v0, :cond_2

    .line 295
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    const/16 v4, 0x8

    invoke-virtual {v0, v4}, Landroid/view/View;->setVisibility(I)V

    .line 296
    iput v3, v1, Landroidx/recyclerview/widget/RecyclerView$LayoutParams;->height:I

    .line 297
    iput v3, v1, Landroidx/recyclerview/widget/RecyclerView$LayoutParams;->width:I

    goto :goto_1

    :cond_2
    const/4 v0, -0x2

    .line 299
    iput v0, v1, Landroidx/recyclerview/widget/RecyclerView$LayoutParams;->height:I

    const/4 v0, -0x1

    .line 300
    iput v0, v1, Landroidx/recyclerview/widget/RecyclerView$LayoutParams;->width:I

    .line 301
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-virtual {v0, v3}, Landroid/view/View;->setVisibility(I)V

    .line 303
    :goto_1
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-virtual {v0, v1}, Landroid/view/View;->setLayoutParams(Landroid/view/ViewGroup$LayoutParams;)V

    .line 305
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->isSelected()Z

    move-result v0

    .line 306
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getName()Ljava/lang/String;

    move-result-object v1

    .line 307
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getId()I

    move-result v4

    .line 309
    invoke-static {}, Lcom/brakefield/infinitestudio/FileManager;->getCustomBrushesPath()Ljava/lang/String;

    move-result-object v5

    new-instance v6, Ljava/lang/StringBuilder;

    invoke-direct {v6}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {v6, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v6

    const-string v7, ".json"

    invoke-virtual {v6, v7}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v6

    invoke-virtual {v6}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v6

    invoke-static {v5, v6}, Lcom/brakefield/infinitestudio/FileManager;->fileExists(Ljava/lang/String;Ljava/lang/String;)Z

    move-result v5

    if-eqz v5, :cond_4

    .line 310
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->isCustom()Z

    move-result v5

    if-eqz v5, :cond_3

    goto :goto_2

    :cond_3
    move v2, v3

    :cond_4
    :goto_2
    if-eqz v2, :cond_5

    .line 313
    invoke-static {}, Lcom/brakefield/infinitestudio/FileManager;->getCustomBrushesPath()Ljava/lang/String;

    move-result-object v5

    new-instance v6, Ljava/lang/StringBuilder;

    const-string v7, "preview_"

    invoke-direct {v6, v7}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v6, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v6

    invoke-virtual {v6}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v6

    invoke-static {v5, v6}, Lcom/brakefield/infinitestudio/FileManager;->getFilePath(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    .line 314
    new-instance v6, Ljava/io/File;

    invoke-direct {v6, v5}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 315
    invoke-virtual {v6}, Ljava/io/File;->exists()Z

    move-result v5

    if-eqz v5, :cond_6

    invoke-virtual {v6}, Ljava/io/File;->length()J

    move-result-wide v7

    const-wide/16 v9, 0x0

    cmp-long v5, v7, v9

    if-lez v5, :cond_6

    iget-object v3, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-static {v3}, Lcom/bumptech/glide/Glide;->with(Landroid/view/View;)Lcom/bumptech/glide/RequestManager;

    move-result-object v3

    invoke-virtual {v3, v6}, Lcom/bumptech/glide/RequestManager;->load(Ljava/io/File;)Lcom/bumptech/glide/RequestBuilder;

    move-result-object v3

    new-instance v5, Lcom/bumptech/glide/signature/ObjectKey;

    invoke-virtual {v6}, Ljava/io/File;->lastModified()J

    move-result-wide v6

    invoke-static {v6, v7}, Ljava/lang/Long;->valueOf(J)Ljava/lang/Long;

    move-result-object v6

    invoke-direct {v5, v6}, Lcom/bumptech/glide/signature/ObjectKey;-><init>(Ljava/lang/Object;)V

    invoke-static {v5}, Lcom/bumptech/glide/request/RequestOptions;->signatureOf(Lcom/bumptech/glide/load/Key;)Lcom/bumptech/glide/request/RequestOptions;

    move-result-object v5

    invoke-virtual {v3, v5}, Lcom/bumptech/glide/RequestBuilder;->apply(Lcom/bumptech/glide/request/BaseRequestOptions;)Lcom/bumptech/glide/RequestBuilder;

    move-result-object v3

    iget-object v5, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v5, v5, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-virtual {v3, v5}, Lcom/bumptech/glide/RequestBuilder;->into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/ViewTarget;

    :cond_5
    move v3, v2

    :cond_6
    if-nez v3, :cond_7

    .line 319
    invoke-static {v4, v1}, Lcom/brakefield/painter/PainterLib;->getBrushPreviewName(ILjava/lang/String;)Ljava/lang/String;

    move-result-object v1

    const-string v2, ".png"

    const/4 v3, 0x0

    sget-object v3, Landroidx/core/database/hzA/JUetN;->olJmmloRSsQqWl:Ljava/lang/String;

    invoke-virtual {v1, v2, v3}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v1

    .line 320
    invoke-static {v1}, Lcom/brakefield/infinitestudio/ResourceHelper;->getDrawableId(Ljava/lang/String;)I

    move-result v1

    .line 321
    iget-object v2, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-static {v2}, Lcom/bumptech/glide/Glide;->with(Landroid/view/View;)Lcom/bumptech/glide/RequestManager;

    move-result-object v2

    invoke-static {v1}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v1

    invoke-virtual {v2, v1}, Lcom/bumptech/glide/RequestManager;->load(Ljava/lang/Integer;)Lcom/bumptech/glide/RequestBuilder;

    move-result-object v1

    sget-object v2, Lcom/bumptech/glide/load/engine/DiskCacheStrategy;->DATA:Lcom/bumptech/glide/load/engine/DiskCacheStrategy;

    invoke-static {v2}, Lcom/bumptech/glide/request/RequestOptions;->diskCacheStrategyOf(Lcom/bumptech/glide/load/engine/DiskCacheStrategy;)Lcom/bumptech/glide/request/RequestOptions;

    move-result-object v2

    invoke-virtual {v1, v2}, Lcom/bumptech/glide/RequestBuilder;->apply(Lcom/bumptech/glide/request/BaseRequestOptions;)Lcom/bumptech/glide/RequestBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v2, v2, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-virtual {v1, v2}, Lcom/bumptech/glide/RequestBuilder;->into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/ViewTarget;

    .line 324
    :cond_7
    iget-boolean v1, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->colorBrush:Z

    .line 325
    iget-object v2, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v2, v2, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushName:Lcom/brakefield/infinitestudio/ui/AutosizeTextView;

    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getDisplayName()Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v2, v3}, Lcom/brakefield/infinitestudio/ui/AutosizeTextView;->setText(Ljava/lang/CharSequence;)V

    .line 327
    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getForegroundColor()I

    move-result v2

    .line 328
    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getForegroundColor()I

    move-result v3

    const/4 v4, 0x0

    if-eqz v0, :cond_9

    .line 331
    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getIconColor()I

    move-result v3

    if-eqz v1, :cond_8

    .line 332
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v0, v0, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-virtual {v0, v4}, Landroid/widget/ImageView;->setColorFilter(Landroid/graphics/ColorFilter;)V

    goto :goto_3

    .line 333
    :cond_8
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v0, v0, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getForegroundColor()I

    move-result v1

    invoke-virtual {v0, v1}, Landroid/widget/ImageView;->setColorFilter(I)V

    goto :goto_3

    .line 335
    :cond_9
    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getIconColor()I

    move-result v2

    if-eqz v1, :cond_a

    .line 336
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v0, v0, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-virtual {v0, v4}, Landroid/widget/ImageView;->setColorFilter(Landroid/graphics/ColorFilter;)V

    goto :goto_3

    .line 337
    :cond_a
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v0, v0, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushPreview:Landroid/widget/ImageView;

    invoke-static {}, Lcom/brakefield/infinitestudio/ui/ThemeManager;->getIconColor()I

    move-result v1

    invoke-virtual {v0, v1}, Landroid/widget/ImageView;->setColorFilter(I)V

    .line 340
    :goto_3
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->binding:Lcom/brakefield/painter/databinding/BrushCardBinding;

    iget-object v0, v0, Lcom/brakefield/painter/databinding/BrushCardBinding;->brushName:Lcom/brakefield/infinitestudio/ui/AutosizeTextView;

    invoke-virtual {v0, v2}, Lcom/brakefield/infinitestudio/ui/AutosizeTextView;->setTextColor(I)V

    .line 342
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-virtual {v0, v3}, Landroid/view/View;->setBackgroundColor(I)V

    .line 343
    iget-object v0, p0, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->itemView:Landroid/view/View;

    invoke-virtual {v0, p1}, Landroid/view/View;->setTag(Ljava/lang/Object;)V

    return-void
.end method

.method public bridge synthetic update(Ljava/lang/Object;)V
    .locals 0

    .line 271
    check-cast p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    invoke-virtual {p0, p1}, Lcom/brakefield/painter/brushes/BrushPackManager$BrushViewHolder;->update(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V

    return-void
.end method
