.class public abstract Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;
.super Ljava/lang/Object;
.source "BrushFolder.java"


# static fields
.field public static final JSON_BRUSHES:Ljava/lang/String; = "brushes"

.field public static final JSON_NAME:Ljava/lang/String; = "name"

.field public static final JSON_SELECTED:Ljava/lang/String; = "selected"

.field public static final JSON_VERSION:Ljava/lang/String; = "version"


# instance fields
.field public brushes:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
            ">;"
        }
    .end annotation
.end field

.field protected customBrushes:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
            ">;"
        }
    .end annotation
.end field

.field public defaultBrushes:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
            ">;"
        }
    .end annotation
.end field

.field public displayName:Ljava/lang/String;

.field public hidden:Z

.field public iconId:I

.field public name:Ljava/lang/String;

.field public quickSelected:I

.field public selected:I


# direct methods
.method public constructor <init>()V
    .locals 2

    .line 23
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const-string v0, ""

    .line 25
    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->name:Ljava/lang/String;

    .line 26
    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    const v0, 0x7f08009b

    .line 28
    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->iconId:I

    .line 30
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    .line 31
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    .line 32
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->customBrushes:Ljava/util/List;

    const/4 v0, 0x0

    .line 34
    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    const/4 v1, -0x1

    .line 35
    iput v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->quickSelected:I

    .line 37
    iput-boolean v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->hidden:Z

    return-void
.end method

.method private getBrushesJSON()Lorg/json/JSONArray;
    .locals 3
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lorg/json/JSONException;
        }
    .end annotation

    .line 83
    new-instance v0, Lorg/json/JSONArray;

    invoke-direct {v0}, Lorg/json/JSONArray;-><init>()V

    .line 84
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 85
    invoke-virtual {v2}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getJSON()Lorg/json/JSONObject;

    move-result-object v2

    invoke-virtual {v0, v2}, Lorg/json/JSONArray;->put(Ljava/lang/Object;)Lorg/json/JSONArray;

    goto :goto_0

    :cond_0
    return-object v0
.end method


# virtual methods
.method public add(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 1

    .line 49
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    invoke-virtual {p0, p1, v0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->insert(Lcom/brakefield/painter/brushes/brushfolders/Brush;I)V

    return-void
.end method

.method public canDropInBrushes()Z
    .locals 1

    const/4 v0, 0x1

    return v0
.end method

.method public canRestore()Z
    .locals 3

    .line 313
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->isAutoGenerated()Z

    move-result v0

    const/4 v1, 0x0

    if-eqz v0, :cond_0

    return v1

    .line 314
    :cond_0
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :cond_1
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_2

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 315
    iget-boolean v2, v2, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    if-eqz v2, :cond_1

    const/4 v0, 0x1

    return v0

    :cond_2
    return v1
.end method

.method public convertAllBrushesToCustomBrushes()V
    .locals 3

    .line 327
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :goto_0
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v1

    if-eqz v1, :cond_0

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    const/4 v2, 0x0

    invoke-virtual {v1, v2}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->setId(I)V

    goto :goto_0

    :cond_0
    return-void
.end method

.method public delete()V
    .locals 3

    .line 198
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getFolderLocation()Ljava/lang/String;

    move-result-object v0

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string v2, ".json"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Lcom/brakefield/infinitestudio/FileManager;->delete(Ljava/lang/String;Ljava/lang/String;)V

    return-void
.end method

.method public deleteBrush(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 1

    .line 206
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    move-result v0

    if-eqz v0, :cond_0

    const/4 v0, 0x1

    iput-boolean v0, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    goto :goto_0

    .line 207
    :cond_0
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->remove(Ljava/lang/Object;)Z

    :goto_0
    return-void
.end method

.method public getBrushes()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lcom/brakefield/painter/brushes/brushfolders/Brush;",
            ">;"
        }
    .end annotation

    .line 45
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    return-object v0
.end method

.method public getFolderLocation()Ljava/lang/String;
    .locals 1

    .line 251
    invoke-static {}, Lcom/brakefield/infinitestudio/FileManager;->getDefaultBrushFoldersPath()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public abstract getId()I
.end method

.method protected getName()Ljava/lang/String;
    .locals 1

    .line 183
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->name:Ljava/lang/String;

    return-object v0
.end method

.method public getSelectedBrush()Lcom/brakefield/painter/brushes/brushfolders/Brush;
    .locals 2

    .line 191
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_0

    const/4 v0, 0x0

    return-object v0

    .line 192
    :cond_0
    iget v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    add-int/lit8 v1, v1, -0x1

    if-le v0, v1, :cond_1

    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    add-int/lit8 v0, v0, -0x1

    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    .line 193
    :cond_1
    iget v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    if-gez v0, :cond_2

    const/4 v0, 0x0

    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    .line 194
    :cond_2
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    iget v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    invoke-interface {v0, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    return-object v0
.end method

.method public getTitle()Ljava/lang/String;
    .locals 1

    .line 202
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    return-object v0
.end method

.method public has(Lcom/brakefield/painter/brushes/brushfolders/Brush;)Z
    .locals 1

    .line 211
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    move-result p1

    return p1
.end method

.method public hasDefaultBrush(Lcom/brakefield/painter/brushes/brushfolders/Brush;)Z
    .locals 1

    .line 215
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    move-result p1

    return p1
.end method

.method public hide(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 1

    .line 219
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->indexOf(Ljava/lang/Object;)I

    move-result p1

    const/4 v0, -0x1

    if-le p1, v0, :cond_0

    .line 221
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    const/4 v0, 0x1

    .line 222
    iput-boolean v0, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    :cond_0
    return-void
.end method

.method public init()V
    .locals 1

    .line 40
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->name:Ljava/lang/String;

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    .line 41
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->loadDisplayName()V

    return-void
.end method

.method public insert(Lcom/brakefield/painter/brushes/brushfolders/Brush;I)V
    .locals 1

    .line 255
    invoke-virtual {p0, p1}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->has(Lcom/brakefield/painter/brushes/brushfolders/Brush;)Z

    move-result v0

    if-nez v0, :cond_0

    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-virtual {p1, p0}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->copy(Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;)Lcom/brakefield/painter/brushes/brushfolders/Brush;

    move-result-object p1

    invoke-interface {v0, p2, p1}, Ljava/util/List;->add(ILjava/lang/Object;)V

    goto :goto_0

    .line 257
    :cond_0
    iget-object p2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {p2, p1}, Ljava/util/List;->indexOf(Ljava/lang/Object;)I

    move-result p1

    const/4 p2, -0x1

    if-le p1, p2, :cond_1

    .line 259
    iget-object p2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {p2, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    const/4 p2, 0x0

    .line 260
    iput-boolean p2, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    :cond_1
    :goto_0
    return-void
.end method

.method public isAutoGenerated()Z
    .locals 1

    const/4 v0, 0x0

    return v0
.end method

.method public isCustom()Z
    .locals 1

    .line 187
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getId()I

    move-result v0

    if-nez v0, :cond_0

    const/4 v0, 0x1

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return v0
.end method

.method public load()V
    .locals 9

    const-string v0, "name"

    const-string/jumbo v1, "version"

    .line 111
    iget-object v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v2}, Ljava/util/List;->clear()V

    .line 113
    :try_start_0
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getFolderLocation()Ljava/lang/String;

    move-result-object v2

    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getName()Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v3

    const-string v4, ".json"

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v3

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-static {v2, v3}, Lcom/brakefield/infinitestudio/FileManager;->getFileInputStream(Ljava/lang/String;Ljava/lang/String;)Ljava/io/FileInputStream;

    move-result-object v2
    :try_end_0
    .catch Ljava/io/FileNotFoundException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    .line 114
    :try_start_1
    new-instance v3, Ljava/io/BufferedReader;

    new-instance v4, Ljava/io/InputStreamReader;

    invoke-direct {v4, v2}, Ljava/io/InputStreamReader;-><init>(Ljava/io/InputStream;)V

    invoke-direct {v3, v4}, Ljava/io/BufferedReader;-><init>(Ljava/io/Reader;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_2

    .line 116
    :try_start_2
    new-instance v4, Ljava/lang/StringBuilder;

    invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V

    .line 118
    :goto_0
    invoke-virtual {v3}, Ljava/io/BufferedReader;->readLine()Ljava/lang/String;

    move-result-object v5

    if-eqz v5, :cond_0

    .line 119
    invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    goto :goto_0

    .line 121
    :cond_0
    invoke-virtual {v3}, Ljava/io/BufferedReader;->close()V

    .line 123
    new-instance v5, Lorg/json/JSONTokener;

    invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v4

    invoke-direct {v5, v4}, Lorg/json/JSONTokener;-><init>(Ljava/lang/String;)V

    invoke-virtual {v5}, Lorg/json/JSONTokener;->nextValue()Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lorg/json/JSONObject;

    .line 125
    invoke-virtual {v4, v1}, Lorg/json/JSONObject;->has(Ljava/lang/String;)Z

    move-result v5

    if-eqz v5, :cond_2

    .line 126
    invoke-virtual {v4, v1}, Lorg/json/JSONObject;->getInt(Ljava/lang/String;)I

    move-result v1

    const/4 v5, 0x3

    if-lt v1, v5, :cond_2

    const-string v1, "brushes"

    .line 127
    invoke-virtual {v4, v1}, Lorg/json/JSONObject;->getJSONArray(Ljava/lang/String;)Lorg/json/JSONArray;

    move-result-object v1

    const/4 v5, 0x0

    .line 128
    :goto_1
    invoke-virtual {v1}, Lorg/json/JSONArray;->length()I

    move-result v6

    if-ge v5, v6, :cond_1

    .line 129
    invoke-virtual {v1, v5}, Lorg/json/JSONArray;->getJSONObject(I)Lorg/json/JSONObject;

    move-result-object v6

    .line 130
    new-instance v7, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    invoke-direct {v7, p0, v6}, Lcom/brakefield/painter/brushes/brushfolders/Brush;-><init>(Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;Lorg/json/JSONObject;)V

    .line 131
    invoke-virtual {p0, v7}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->add(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V

    add-int/lit8 v5, v5, 0x1

    goto :goto_1

    :cond_1
    const-string/jumbo v1, "selected"

    .line 133
    invoke-virtual {v4, v1}, Lorg/json/JSONObject;->getInt(Ljava/lang/String;)I

    move-result v1

    iput v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    .line 137
    :cond_2
    invoke-virtual {v4, v0}, Lorg/json/JSONObject;->has(Ljava/lang/String;)Z

    move-result v1

    if-eqz v1, :cond_3

    .line 138
    invoke-virtual {v4, v0}, Lorg/json/JSONObject;->getString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    .line 141
    :cond_3
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    .line 142
    new-instance v1, Ljava/util/ArrayList;

    iget-object v4, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-direct {v1, v4}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V

    .line 144
    iget-object v4, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v4

    :goto_2
    invoke-interface {v4}, Ljava/util/Iterator;->hasNext()Z

    move-result v5

    if-eqz v5, :cond_6

    invoke-interface {v4}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 145
    iget-object v6, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v6}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v6

    :cond_4
    invoke-interface {v6}, Ljava/util/Iterator;->hasNext()Z

    move-result v7

    if-eqz v7, :cond_5

    invoke-interface {v6}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v7

    check-cast v7, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 146
    invoke-virtual {v5, v7}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->compareTo(Lcom/brakefield/painter/brushes/brushfolders/Brush;)I

    move-result v8

    if-nez v8, :cond_4

    .line 147
    invoke-virtual {v1, v7}, Ljava/util/ArrayList;->remove(Ljava/lang/Object;)Z

    .line 151
    :cond_5
    invoke-virtual {v0, v5}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    goto :goto_2

    .line 154
    :cond_6
    invoke-virtual {v0, v1}, Ljava/util/ArrayList;->addAll(Ljava/util/Collection;)Z

    .line 156
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->clear()V

    .line 157
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_0

    .line 159
    :try_start_3
    invoke-virtual {v3}, Ljava/io/BufferedReader;->close()V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    if-eqz v2, :cond_8

    :try_start_4
    invoke-virtual {v2}, Ljava/io/InputStream;->close()V
    :try_end_4
    .catch Ljava/io/FileNotFoundException; {:try_start_4 .. :try_end_4} :catch_1
    .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0

    goto :goto_5

    :catchall_0
    move-exception v0

    .line 113
    :try_start_5
    invoke-virtual {v3}, Ljava/io/BufferedReader;->close()V
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_1

    goto :goto_3

    :catchall_1
    move-exception v1

    :try_start_6
    invoke-virtual {v0, v1}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :goto_3
    throw v0
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_2

    :catchall_2
    move-exception v0

    if-eqz v2, :cond_7

    :try_start_7
    invoke-virtual {v2}, Ljava/io/InputStream;->close()V
    :try_end_7
    .catchall {:try_start_7 .. :try_end_7} :catchall_3

    goto :goto_4

    :catchall_3
    move-exception v1

    :try_start_8
    invoke-virtual {v0, v1}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :cond_7
    :goto_4
    throw v0
    :try_end_8
    .catch Ljava/io/FileNotFoundException; {:try_start_8 .. :try_end_8} :catch_1
    .catch Ljava/lang/Exception; {:try_start_8 .. :try_end_8} :catch_0

    :catch_0
    move-exception v0

    .line 162
    invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V

    .line 165
    :catch_1
    :cond_8
    :goto_5
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :cond_9
    :goto_6
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v1

    if-eqz v1, :cond_a

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 166
    iget-object v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v2, v1}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    move-result v2

    if-nez v2, :cond_9

    .line 167
    iget-object v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v2, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    goto :goto_6

    :cond_a
    return-void
.end method

.method public loadDisplayName()V
    .locals 5

    const-string v0, "name"

    .line 91
    :try_start_0
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getFolderLocation()Ljava/lang/String;

    move-result-object v1

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getName()Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    const-string v3, ".json"

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v1, v2}, Lcom/brakefield/infinitestudio/FileManager;->getFileInputStream(Ljava/lang/String;Ljava/lang/String;)Ljava/io/FileInputStream;

    move-result-object v1
    :try_end_0
    .catch Ljava/io/FileNotFoundException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    .line 92
    :try_start_1
    new-instance v2, Ljava/io/BufferedReader;

    new-instance v3, Ljava/io/InputStreamReader;

    invoke-direct {v3, v1}, Ljava/io/InputStreamReader;-><init>(Ljava/io/InputStream;)V

    invoke-direct {v2, v3}, Ljava/io/BufferedReader;-><init>(Ljava/io/Reader;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_2

    .line 93
    :try_start_2
    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    .line 95
    :goto_0
    invoke-virtual {v2}, Ljava/io/BufferedReader;->readLine()Ljava/lang/String;

    move-result-object v4

    if-eqz v4, :cond_0

    .line 96
    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    goto :goto_0

    .line 98
    :cond_0
    new-instance v4, Lorg/json/JSONTokener;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-direct {v4, v3}, Lorg/json/JSONTokener;-><init>(Ljava/lang/String;)V

    invoke-virtual {v4}, Lorg/json/JSONTokener;->nextValue()Ljava/lang/Object;

    move-result-object v3

    check-cast v3, Lorg/json/JSONObject;

    .line 99
    invoke-virtual {v3, v0}, Lorg/json/JSONObject;->has(Ljava/lang/String;)Z

    move-result v4

    if-eqz v4, :cond_1

    .line 100
    invoke-virtual {v3, v0}, Lorg/json/JSONObject;->getString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_0

    .line 102
    :cond_1
    :try_start_3
    invoke-virtual {v2}, Ljava/io/BufferedReader;->close()V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    if-eqz v1, :cond_3

    :try_start_4
    invoke-virtual {v1}, Ljava/io/InputStream;->close()V
    :try_end_4
    .catch Ljava/io/FileNotFoundException; {:try_start_4 .. :try_end_4} :catch_1
    .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0

    goto :goto_3

    :catchall_0
    move-exception v0

    .line 91
    :try_start_5
    invoke-virtual {v2}, Ljava/io/BufferedReader;->close()V
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_1

    goto :goto_1

    :catchall_1
    move-exception v2

    :try_start_6
    invoke-virtual {v0, v2}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :goto_1
    throw v0
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_2

    :catchall_2
    move-exception v0

    if-eqz v1, :cond_2

    :try_start_7
    invoke-virtual {v1}, Ljava/io/InputStream;->close()V
    :try_end_7
    .catchall {:try_start_7 .. :try_end_7} :catchall_3

    goto :goto_2

    :catchall_3
    move-exception v1

    :try_start_8
    invoke-virtual {v0, v1}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :cond_2
    :goto_2
    throw v0
    :try_end_8
    .catch Ljava/io/FileNotFoundException; {:try_start_8 .. :try_end_8} :catch_1
    .catch Ljava/lang/Exception; {:try_start_8 .. :try_end_8} :catch_0

    :catch_0
    move-exception v0

    .line 105
    invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V

    :catch_1
    :cond_3
    :goto_3
    return-void
.end method

.method public refresh()V
    .locals 3

    .line 53
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->clear()V

    .line 54
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->load()V

    .line 55
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->customBrushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :cond_0
    :goto_0
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v1

    if-eqz v1, :cond_1

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 56
    iget-object v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v2, v1}, Ljava/util/List;->contains(Ljava/lang/Object;)Z

    move-result v2

    if-nez v2, :cond_0

    invoke-virtual {p0, v1}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->add(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V

    goto :goto_0

    :cond_1
    return-void
.end method

.method public refreshSelectedDisplayName()V
    .locals 3

    .line 321
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :cond_0
    :goto_0
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v1

    if-eqz v1, :cond_1

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 322
    invoke-virtual {v1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->isSelected()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-virtual {v1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->refreshDisplayName()V

    goto :goto_0

    :cond_1
    return-void
.end method

.method public rename(Ljava/lang/String;)V
    .locals 0

    .line 266
    iput-object p1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    .line 267
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->save()V

    return-void
.end method

.method public restore()V
    .locals 3

    .line 301
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->canRestore()Z

    move-result v0

    if-nez v0, :cond_0

    return-void

    .line 303
    :cond_0
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getFolderLocation()Ljava/lang/String;

    move-result-object v0

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string v2, ".json"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Lcom/brakefield/infinitestudio/FileManager;->delete(Ljava/lang/String;Ljava/lang/String;)V

    .line 305
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->clear()V

    .line 306
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->defaultBrushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->clear()V

    .line 307
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->customBrushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->clear()V

    .line 309
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->init()V

    return-void
.end method

.method public save()V
    .locals 3

    .line 173
    :try_start_0
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getFolderLocation()Ljava/lang/String;

    move-result-object v0

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string v2, ".json"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Lcom/brakefield/infinitestudio/FileManager;->getFileOutputStream(Ljava/lang/String;Ljava/lang/String;)Ljava/io/FileOutputStream;

    move-result-object v0
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    .line 174
    :try_start_1
    new-instance v1, Ljava/io/OutputStreamWriter;

    invoke-direct {v1, v0}, Ljava/io/OutputStreamWriter;-><init>(Ljava/io/OutputStream;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_2

    .line 175
    :try_start_2
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->toJSON()Lorg/json/JSONObject;

    move-result-object v2

    .line 176
    invoke-virtual {v2}, Lorg/json/JSONObject;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/io/Writer;->write(Ljava/lang/String;)V
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_0

    .line 177
    :try_start_3
    invoke-virtual {v1}, Ljava/io/Writer;->close()V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    if-eqz v0, :cond_1

    :try_start_4
    invoke-virtual {v0}, Ljava/io/OutputStream;->close()V
    :try_end_4
    .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0

    goto :goto_2

    :catchall_0
    move-exception v2

    .line 173
    :try_start_5
    invoke-virtual {v1}, Ljava/io/Writer;->close()V
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_1

    goto :goto_0

    :catchall_1
    move-exception v1

    :try_start_6
    invoke-virtual {v2, v1}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :goto_0
    throw v2
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_2

    :catchall_2
    move-exception v1

    if-eqz v0, :cond_0

    :try_start_7
    invoke-virtual {v0}, Ljava/io/OutputStream;->close()V
    :try_end_7
    .catchall {:try_start_7 .. :try_end_7} :catchall_3

    goto :goto_1

    :catchall_3
    move-exception v0

    :try_start_8
    invoke-virtual {v1, v0}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    :cond_0
    :goto_1
    throw v1
    :try_end_8
    .catch Ljava/lang/Exception; {:try_start_8 .. :try_end_8} :catch_0

    :catch_0
    move-exception v0

    .line 178
    invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V

    :cond_1
    :goto_2
    return-void
.end method

.method public select(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 3

    const/4 v0, 0x0

    .line 272
    :goto_0
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    const/4 v2, -0x1

    if-ge v0, v1, :cond_1

    .line 273
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 274
    invoke-virtual {v1, p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->compareTo(Lcom/brakefield/painter/brushes/brushfolders/Brush;)I

    move-result v1

    if-nez v1, :cond_0

    goto :goto_1

    :cond_0
    add-int/lit8 v0, v0, 0x1

    goto :goto_0

    :cond_1
    move v0, v2

    :goto_1
    if-ne v0, v2, :cond_2

    return-void

    .line 280
    :cond_2
    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    .line 281
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getSelectedBrush()Lcom/brakefield/painter/brushes/brushfolders/Brush;

    move-result-object p1

    .line 282
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getId()I

    move-result v0

    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getName()Ljava/lang/String;

    move-result-object p1

    invoke-static {v0, p1}, Lcom/brakefield/painter/PainterLib;->setBrushType(ILjava/lang/String;)V

    .line 283
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->save()V

    return-void
.end method

.method public set(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 3

    const/4 v0, 0x0

    .line 235
    :goto_0
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_4

    .line 236
    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    .line 237
    invoke-virtual {v1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getName()Ljava/lang/String;

    move-result-object v1

    if-nez v1, :cond_0

    goto :goto_1

    .line 239
    :cond_0
    invoke-virtual {p1}, Lcom/brakefield/painter/brushes/brushfolders/Brush;->getName()Ljava/lang/String;

    move-result-object v2

    if-nez v2, :cond_1

    return-void

    .line 241
    :cond_1
    invoke-virtual {v1, v2}, Ljava/lang/String;->compareTo(Ljava/lang/String;)I

    move-result v1

    if-nez v1, :cond_3

    .line 242
    iget p1, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    .line 243
    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    if-eq p1, v0, :cond_2

    .line 244
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->save()V

    :cond_2
    return-void

    :cond_3
    :goto_1
    add-int/lit8 v0, v0, 0x1

    goto :goto_0

    :cond_4
    return-void
.end method

.method public toJSON()Lorg/json/JSONObject;
    .locals 3
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lorg/json/JSONException;
        }
    .end annotation

    .line 72
    new-instance v0, Lorg/json/JSONObject;

    invoke-direct {v0}, Lorg/json/JSONObject;-><init>()V

    const-string/jumbo v1, "version"

    const/4 v2, 0x3

    .line 74
    invoke-virtual {v0, v1, v2}, Lorg/json/JSONObject;->put(Ljava/lang/String;I)Lorg/json/JSONObject;

    const-string v1, "brushes"

    .line 75
    invoke-direct {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->getBrushesJSON()Lorg/json/JSONArray;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Lorg/json/JSONObject;->put(Ljava/lang/String;Ljava/lang/Object;)Lorg/json/JSONObject;

    const-string/jumbo v1, "selected"

    .line 76
    iget v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->selected:I

    invoke-virtual {v0, v1, v2}, Lorg/json/JSONObject;->put(Ljava/lang/String;I)Lorg/json/JSONObject;

    const-string v1, "name"

    .line 77
    iget-object v2, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->displayName:Ljava/lang/String;

    invoke-virtual {v0, v1, v2}, Lorg/json/JSONObject;->put(Ljava/lang/String;Ljava/lang/Object;)Lorg/json/JSONObject;

    return-object v0
.end method

.method public unhide(Lcom/brakefield/painter/brushes/brushfolders/Brush;)V
    .locals 1

    .line 227
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->indexOf(Ljava/lang/Object;)I

    move-result p1

    const/4 v0, -0x1

    if-le p1, v0, :cond_0

    .line 229
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->brushes:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    const/4 v0, 0x0

    .line 230
    iput-boolean v0, p1, Lcom/brakefield/painter/brushes/brushfolders/Brush;->hidden:Z

    :cond_0
    return-void
.end method
