.class public Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;
.super Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;
.source "UserCreatedFolder.java"


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 11
    invoke-direct {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;-><init>()V

    return-void
.end method


# virtual methods
.method public canDropInBrushes()Z
    .locals 1

    const/4 v0, 0x0

    return v0
.end method

.method public getId()I
    .locals 1

    const/16 v0, 0x64

    return v0
.end method

.method public init()V
    .locals 1

    const v0, 0x7f120083

    .line 14
    invoke-static {v0}, Lcom/brakefield/infinitestudio/Strings;->get(I)Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->name:Ljava/lang/String;

    const v0, 0x7f0801e1

    .line 15
    iput v0, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->iconId:I

    .line 16
    invoke-super {p0}, Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;->init()V

    return-void
.end method

.method public isAutoGenerated()Z
    .locals 1

    const/4 v0, 0x1

    return v0
.end method

.method public load()V
    .locals 2

    .line 51
    invoke-virtual {p0}, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->refreshCustomBrushes()V

    .line 52
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->brushes:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->clear()V

    .line 53
    iget-object v0, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->brushes:Ljava/util/List;

    iget-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->customBrushes:Ljava/util/List;

    invoke-interface {v0, v1}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z

    return-void
.end method

.method public refreshCustomBrushes()V
    .locals 8

    .line 20
    invoke-static {}, Lcom/brakefield/infinitestudio/FileManager;->getCreatedBrushesPath()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lcom/brakefield/infinitestudio/FileManager;->getFilesSorted(Ljava/lang/String;)[Ljava/lang/String;

    move-result-object v0

    .line 21
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    if-eqz v0, :cond_1

    .line 23
    array-length v2, v0

    const/4 v3, 0x0

    move v4, v3

    :goto_0
    if-ge v4, v2, :cond_1

    aget-object v5, v0, v4

    const-string v6, ".json"

    invoke-virtual {v5, v6}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v7

    if-eqz v7, :cond_0

    .line 24
    invoke-virtual {v5, v6}, Ljava/lang/String;->split(Ljava/lang/String;)[Ljava/lang/String;

    move-result-object v5

    .line 25
    array-length v6, v5

    if-lez v6, :cond_0

    .line 26
    new-instance v6, Lcom/brakefield/painter/brushes/brushfolders/Brush;

    aget-object v5, v5, v3

    invoke-direct {v6, p0, v3, v5}, Lcom/brakefield/painter/brushes/brushfolders/Brush;-><init>(Lcom/brakefield/painter/brushes/brushfolders/BrushFolder;ILjava/lang/String;)V

    .line 27
    invoke-interface {v1, v6}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    :cond_0
    add-int/lit8 v4, v4, 0x1

    goto :goto_0

    .line 31
    :cond_1
    iput-object v1, p0, Lcom/brakefield/painter/brushes/brushfolders/UserCreatedFolder;->customBrushes:Ljava/util/List;

    return-void
.end method

.method public save()V
    .locals 0

    return-void
.end method
